// This file is generated by groth16_solana::vk::circom.
// Do not edit by hand.

// INSECURE TEST SETUP: the secret setup randomness is public or
// untrusted. Whoever knows it can make this verifying key accept a
// proof for any public inputs without a valid witness. Do not deploy
// it to devnet or mainnet.

use groth16_solana::groth16::Groth16Verifyingkey;

#[rustfmt::skip]
pub const VERIFYINGKEY: Groth16Verifyingkey = Groth16Verifyingkey {
	nr_pubinputs: 5,

	vk_alpha_g1: [36u8, 82u8, 41u8, 217u8, 176u8, 118u8, 179u8, 192u8, 232u8, 164u8, 215u8, 11u8, 222u8, 140u8, 28u8, 204u8, 255u8, 160u8, 138u8, 159u8, 174u8, 117u8, 87u8, 177u8, 101u8, 179u8, 176u8, 219u8, 214u8, 83u8, 226u8, 199u8, 37u8, 62u8, 200u8, 89u8, 136u8, 219u8, 184u8, 78u8, 70u8, 233u8, 75u8, 94u8, 250u8, 51u8, 115u8, 180u8, 122u8, 0u8, 11u8, 74u8, 198u8, 200u8, 107u8, 45u8, 75u8, 121u8, 141u8, 39u8, 74u8, 24u8, 35u8, 2u8],

	vk_beta_g2: [7u8, 9u8, 10u8, 130u8, 232u8, 250u8, 187u8, 211u8, 146u8, 153u8, 190u8, 36u8, 112u8, 91u8, 146u8, 207u8, 32u8, 142u8, 232u8, 179u8, 72u8, 127u8, 111u8, 43u8, 57u8, 255u8, 39u8, 151u8, 138u8, 41u8, 161u8, 219u8, 36u8, 36u8, 188u8, 193u8, 246u8, 10u8, 84u8, 114u8, 104u8, 95u8, 213u8, 7u8, 5u8, 178u8, 128u8, 150u8, 38u8, 225u8, 112u8, 18u8, 10u8, 202u8, 244u8, 65u8, 225u8, 51u8, 162u8, 189u8, 94u8, 97u8, 210u8, 68u8, 10u8, 225u8, 19u8, 92u8, 255u8, 218u8, 242u8, 39u8, 197u8, 220u8, 38u8, 103u8, 64u8, 96u8, 122u8, 169u8, 48u8, 188u8, 59u8, 217u8, 45u8, 220u8, 43u8, 19u8, 80u8, 134u8, 217u8, 218u8, 45u8, 253u8, 62u8, 42u8, 43u8, 134u8, 133u8, 159u8, 211u8, 213u8, 92u8, 157u8, 21u8, 15u8, 179u8, 240u8, 174u8, 186u8, 121u8, 136u8, 38u8, 73u8, 61u8, 215u8, 61u8, 53u8, 122u8, 176u8, 249u8, 253u8, 172u8, 237u8, 159u8, 200u8, 24u8, 41u8],

	vk_gamma_g2: [25u8, 142u8, 147u8, 147u8, 146u8, 13u8, 72u8, 58u8, 114u8, 96u8, 191u8, 183u8, 49u8, 251u8, 93u8, 37u8, 241u8, 170u8, 73u8, 51u8, 53u8, 169u8, 231u8, 18u8, 151u8, 228u8, 133u8, 183u8, 174u8, 243u8, 18u8, 194u8, 24u8, 0u8, 222u8, 239u8, 18u8, 31u8, 30u8, 118u8, 66u8, 106u8, 0u8, 102u8, 94u8, 92u8, 68u8, 121u8, 103u8, 67u8, 34u8, 212u8, 247u8, 94u8, 218u8, 221u8, 70u8, 222u8, 189u8, 92u8, 217u8, 146u8, 246u8, 237u8, 9u8, 6u8, 137u8, 208u8, 88u8, 95u8, 240u8, 117u8, 236u8, 158u8, 153u8, 173u8, 105u8, 12u8, 51u8, 149u8, 188u8, 75u8, 49u8, 51u8, 112u8, 179u8, 142u8, 243u8, 85u8, 172u8, 218u8, 220u8, 209u8, 34u8, 151u8, 91u8, 18u8, 200u8, 94u8, 165u8, 219u8, 140u8, 109u8, 235u8, 74u8, 171u8, 113u8, 128u8, 141u8, 203u8, 64u8, 143u8, 227u8, 209u8, 231u8, 105u8, 12u8, 67u8, 211u8, 123u8, 76u8, 230u8, 204u8, 1u8, 102u8, 250u8, 125u8, 170u8],

	vk_delta_g2: [37u8, 44u8, 17u8, 229u8, 98u8, 250u8, 237u8, 78u8, 175u8, 254u8, 7u8, 28u8, 145u8, 97u8, 244u8, 23u8, 216u8, 62u8, 230u8, 185u8, 33u8, 243u8, 94u8, 236u8, 194u8, 165u8, 14u8, 10u8, 20u8, 151u8, 150u8, 37u8, 2u8, 4u8, 215u8, 227u8, 170u8, 225u8, 68u8, 214u8, 26u8, 167u8, 25u8, 192u8, 29u8, 48u8, 187u8, 150u8, 62u8, 252u8, 92u8, 7u8, 204u8, 158u8, 142u8, 157u8, 107u8, 251u8, 185u8, 156u8, 167u8, 139u8, 175u8, 54u8, 46u8, 205u8, 179u8, 96u8, 57u8, 77u8, 62u8, 223u8, 245u8, 178u8, 20u8, 207u8, 139u8, 112u8, 29u8, 77u8, 141u8, 99u8, 150u8, 195u8, 133u8, 137u8, 178u8, 122u8, 126u8, 226u8, 72u8, 158u8, 119u8, 15u8, 68u8, 200u8, 26u8, 223u8, 191u8, 74u8, 106u8, 214u8, 48u8, 29u8, 34u8, 200u8, 164u8, 151u8, 127u8, 250u8, 137u8, 61u8, 90u8, 216u8, 185u8, 179u8, 190u8, 64u8, 59u8, 150u8, 172u8, 254u8, 167u8, 223u8, 160u8, 106u8, 144u8, 105u8],

	vk_ic: &[
		[13u8, 48u8, 34u8, 158u8, 224u8, 195u8, 129u8, 47u8, 85u8, 51u8, 163u8, 226u8, 217u8, 42u8, 232u8, 89u8, 66u8, 10u8, 69u8, 38u8, 181u8, 171u8, 1u8, 236u8, 6u8, 57u8, 172u8, 68u8, 66u8, 60u8, 108u8, 153u8, 2u8, 64u8, 101u8, 126u8, 89u8, 74u8, 0u8, 124u8, 103u8, 59u8, 169u8, 67u8, 128u8, 166u8, 145u8, 154u8, 209u8, 8u8, 39u8, 122u8, 172u8, 11u8, 164u8, 138u8, 117u8, 196u8, 199u8, 220u8, 236u8, 162u8, 105u8, 161u8],
		[0u8, 69u8, 46u8, 250u8, 32u8, 33u8, 139u8, 235u8, 227u8, 226u8, 46u8, 80u8, 91u8, 112u8, 63u8, 197u8, 48u8, 16u8, 198u8, 57u8, 110u8, 208u8, 240u8, 31u8, 164u8, 153u8, 239u8, 56u8, 170u8, 69u8, 233u8, 166u8, 30u8, 161u8, 28u8, 91u8, 140u8, 90u8, 33u8, 135u8, 54u8, 221u8, 199u8, 20u8, 170u8, 73u8, 207u8, 41u8, 194u8, 157u8, 55u8, 213u8, 196u8, 224u8, 31u8, 157u8, 65u8, 102u8, 42u8, 229u8, 232u8, 183u8, 95u8, 100u8],
		[42u8, 179u8, 194u8, 115u8, 224u8, 144u8, 238u8, 219u8, 114u8, 89u8, 218u8, 234u8, 83u8, 40u8, 188u8, 86u8, 228u8, 187u8, 236u8, 72u8, 2u8, 189u8, 171u8, 108u8, 55u8, 193u8, 15u8, 32u8, 100u8, 85u8, 185u8, 49u8, 16u8, 29u8, 51u8, 108u8, 180u8, 168u8, 115u8, 76u8, 143u8, 147u8, 48u8, 102u8, 166u8, 112u8, 219u8, 70u8, 6u8, 25u8, 244u8, 162u8, 80u8, 46u8, 146u8, 78u8, 115u8, 221u8, 107u8, 112u8, 112u8, 56u8, 211u8, 156u8],
		[8u8, 21u8, 6u8, 141u8, 236u8, 91u8, 211u8, 112u8, 233u8, 16u8, 61u8, 109u8, 71u8, 210u8, 101u8, 224u8, 188u8, 8u8, 43u8, 79u8, 148u8, 105u8, 192u8, 36u8, 147u8, 157u8, 238u8, 110u8, 178u8, 8u8, 4u8, 212u8, 47u8, 248u8, 186u8, 174u8, 83u8, 253u8, 194u8, 105u8, 213u8, 129u8, 154u8, 162u8, 45u8, 133u8, 53u8, 236u8, 107u8, 163u8, 223u8, 121u8, 191u8, 217u8, 49u8, 86u8, 178u8, 213u8, 201u8, 63u8, 143u8, 245u8, 141u8, 38u8],
		[2u8, 156u8, 251u8, 151u8, 103u8, 31u8, 117u8, 160u8, 169u8, 255u8, 71u8, 152u8, 136u8, 90u8, 103u8, 195u8, 157u8, 93u8, 119u8, 216u8, 133u8, 80u8, 159u8, 30u8, 22u8, 231u8, 104u8, 63u8, 127u8, 199u8, 165u8, 139u8, 30u8, 162u8, 122u8, 233u8, 126u8, 251u8, 132u8, 222u8, 233u8, 133u8, 95u8, 71u8, 4u8, 20u8, 44u8, 34u8, 151u8, 252u8, 236u8, 8u8, 81u8, 183u8, 228u8, 98u8, 197u8, 190u8, 200u8, 164u8, 194u8, 243u8, 66u8, 134u8],
		[4u8, 145u8, 201u8, 106u8, 109u8, 69u8, 77u8, 212u8, 56u8, 27u8, 171u8, 208u8, 51u8, 148u8, 159u8, 176u8, 178u8, 166u8, 221u8, 26u8, 238u8, 232u8, 14u8, 51u8, 254u8, 70u8, 215u8, 213u8, 86u8, 231u8, 91u8, 223u8, 28u8, 19u8, 227u8, 161u8, 60u8, 50u8, 171u8, 18u8, 36u8, 45u8, 222u8, 221u8, 98u8, 219u8, 30u8, 149u8, 157u8, 100u8, 215u8, 68u8, 227u8, 239u8, 167u8, 128u8, 43u8, 204u8, 92u8, 210u8, 222u8, 227u8, 55u8, 82u8],
	],

	vk_commitment: None,
};

/// SHA-256 of the proving key file this verifying key was generated with.
#[allow(dead_code)]
#[rustfmt::skip]
pub const VERIFYINGKEY_PROVING_KEY_SHA256: [u8; 32] = [129u8, 148u8, 31u8, 124u8, 52u8, 235u8, 175u8, 34u8, 191u8, 74u8, 237u8, 221u8, 33u8, 38u8, 69u8, 62u8, 96u8, 242u8, 246u8, 26u8, 236u8, 158u8, 194u8, 162u8, 82u8, 189u8, 212u8, 145u8, 187u8, 164u8, 6u8, 231u8];

/// `true` for a test setup whose secret randomness is public or untrusted:
/// whoever knows it can make this key accept a proof for any public
/// inputs without a valid witness. Must not be deployed to devnet or
/// mainnet.
#[allow(dead_code)]
pub const VERIFYINGKEY_INSECURE_TEST_SETUP: bool = true;

/// The two consts above as a delimited string, exported so it stays in
/// the program binary; read it back with
/// `groth16_solana::vk::setup::find_setup_txts`.
#[unsafe(export_name = "groth16_solana_vk_setup_f2299b2895ab060a")]
#[rustfmt::skip]
pub static VERIFYINGKEY_SETUP_TXT: &str = "=======BEGIN GROTH16 VK SETUP V1=======\x00name\x00VERIFYINGKEY\x00insecure_test_setup\x00true\x00proving_key_sha256\x0081941f7c34ebaf22bf4aeddd2126453e60f2f61aec9ec2a252bdd491bba406e7\x00=======END GROTH16 VK SETUP V1=======\x00";

#[cfg(not(feature = "insecure-test-setup"))]
compile_error!("VERIFYINGKEY comes from an insecure test setup: whoever knows its setup randomness can make it accept a proof for any public inputs. Enable the `insecure-test-setup` feature only in test builds, not for a devnet or mainnet deployment.");
