//! # groth16-solana
//!
//! Groth16 zero-knowledge proof verification with Solana altbn254 syscalls.
//!
//! Verification takes less than 200,000 compute units.
//!
//! The syscalls are contained in Solana releases 1.18.x onwards and are active on mainnet-beta.
//!
//! Inputs need to be in u8 arrays in big endian.
//!
//! See functional test as an example how to use this library.
//!
//! This crate is compatible with Groth16 proofs of circom circuits.
//!
//! The verifier file can be generated with the java script script from a verifyingkey.json file generated by snarkjs.

#![no_std]

extern crate alloc;

pub mod decompression;
pub mod errors;
pub mod groth16;
pub mod syscalls;

#[cfg(feature = "vk")]
pub mod vk_parser;

#[cfg(feature = "circom")]
pub mod proof_parser;

#[cfg(feature = "bsb22")]
pub mod hash_to_field;

#[cfg(feature = "bsb22")]
pub mod gnark_vk_parser;
