//! # groth16-solana
//!
//! Groth16 zero-knowledge proof verification with Solana altbn254 syscalls.
//!
//! Verification takes less than 200,000 compute units.
//!
//! The syscalls are contained in Solana releases 1.18.x onwards and are active on mainnet-beta.
//!
//! Inputs need to be in u8 arrays in big endian.
//!
//! See functional test as an example how to use this library.
//!
//! This crate is compatible with Groth16 proofs of circom circuits.
//!
//! The verifier file can be generated with the java script script from a verifyingkey.json file generated by snarkjs.

#![no_std]

// The on-chain verification path (default and `bsb22` features on the
// Solana target) is heap-allocation-free; `alloc` is only needed by
// host-side tooling (vk parsers, proof parser) and tests. Gating the
// extern makes that a compile-time guarantee: any allocation
// reintroduced into on-chain code fails to build for SBF.
#[cfg(any(not(target_os = "solana"), feature = "circom"))]
extern crate alloc;

// proptest (dev-dependency) expands to std-using code; the crate
// itself stays no_std, this only affects `cargo test` builds.
#[cfg(test)]
extern crate std;

pub mod decompression;
pub mod errors;
pub mod groth16;
pub(crate) mod syscalls;

#[cfg(feature = "circom")]
pub mod proof_parser;

#[cfg(feature = "bsb22")]
pub(crate) mod hash_to_field;

// Baked, reproducible BSB22 fixture bytes shared by the lib-internal
// unit tests (see the module docs for regeneration). Lives in
// tests/gnark-ffi/ next to the generator that produces it because it
// is test-only data, not crate source; the `#[path]` include is what
// lets `#[cfg(test)]` modules in src/ reach it as a crate-internal
// module.
#[cfg(all(test, feature = "bsb22"))]
#[path = "../tests/gnark-ffi/test_fixtures.rs"]
pub(crate) mod test_fixtures;

/// Test-only escape hatch (`bsb22-test` feature): the differential
/// proptests in `tests/gnark-ffi/` compare this against gnark-crypto's
/// `fr/hash_to_field` via FFI. Not a stable API surface.
#[cfg(feature = "bsb22-test")]
pub use hash_to_field::hash_to_field_bn254_fr;

/// Verifying-key parsers and Rust-const generators, one submodule per
/// proving stack: [`vk::circom`] for snarkjs JSON keys, [`vk::gnark`]
/// for gnark `WriteRawTo` binaries (incl. BSB22 commitment keys).
pub mod vk {
    #[cfg(feature = "vk")]
    pub mod circom;

    // Host-only: the parser owns its IC column as a `Vec` and the
    // generator writes files; neither belongs in an SBF build, and
    // excluding them keeps the on-chain build free of `alloc`.
    #[cfg(all(feature = "bsb22", not(target_os = "solana")))]
    pub mod gnark;
}
